// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EvBase.proto

package com.github.kylegagnon99.events;

public final class EvBaseOuterClass {
  private EvBaseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EvBaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:events.EvBase)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 source = 1;</code>
     * @return The source.
     */
    int getSource();

    /**
     * <code>uint32 destination = 2;</code>
     * @return The destination.
     */
    int getDestination();

    /**
     * <code>.events.EvSimpleMessage evSimpleMessage = 3;</code>
     * @return Whether the evSimpleMessage field is set.
     */
    boolean hasEvSimpleMessage();
    /**
     * <code>.events.EvSimpleMessage evSimpleMessage = 3;</code>
     * @return The evSimpleMessage.
     */
    com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage getEvSimpleMessage();
    /**
     * <code>.events.EvSimpleMessage evSimpleMessage = 3;</code>
     */
    com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessageOrBuilder getEvSimpleMessageOrBuilder();

    /**
     * <code>.events.EvSimpleNumber evSimpleNumber = 4;</code>
     * @return Whether the evSimpleNumber field is set.
     */
    boolean hasEvSimpleNumber();
    /**
     * <code>.events.EvSimpleNumber evSimpleNumber = 4;</code>
     * @return The evSimpleNumber.
     */
    com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber getEvSimpleNumber();
    /**
     * <code>.events.EvSimpleNumber evSimpleNumber = 4;</code>
     */
    com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumberOrBuilder getEvSimpleNumberOrBuilder();

    public com.github.kylegagnon99.events.EvBaseOuterClass.EvBase.EventsCase getEventsCase();
  }
  /**
   * Protobuf type {@code events.EvBase}
   */
  public static final class EvBase extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:events.EvBase)
      EvBaseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EvBase.newBuilder() to construct.
    private EvBase(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EvBase() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EvBase();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EvBase(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              source_ = input.readUInt32();
              break;
            }
            case 16: {

              destination_ = input.readUInt32();
              break;
            }
            case 26: {
              com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage.Builder subBuilder = null;
              if (eventsCase_ == 3) {
                subBuilder = ((com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage) events_).toBuilder();
              }
              events_ =
                  input.readMessage(com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage) events_);
                events_ = subBuilder.buildPartial();
              }
              eventsCase_ = 3;
              break;
            }
            case 34: {
              com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber.Builder subBuilder = null;
              if (eventsCase_ == 4) {
                subBuilder = ((com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber) events_).toBuilder();
              }
              events_ =
                  input.readMessage(com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber) events_);
                events_ = subBuilder.buildPartial();
              }
              eventsCase_ = 4;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.kylegagnon99.events.EvBaseOuterClass.internal_static_events_EvBase_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.kylegagnon99.events.EvBaseOuterClass.internal_static_events_EvBase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.kylegagnon99.events.EvBaseOuterClass.EvBase.class, com.github.kylegagnon99.events.EvBaseOuterClass.EvBase.Builder.class);
    }

    private int eventsCase_ = 0;
    private java.lang.Object events_;
    public enum EventsCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      EVSIMPLEMESSAGE(3),
      EVSIMPLENUMBER(4),
      EVENTS_NOT_SET(0);
      private final int value;
      private EventsCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EventsCase valueOf(int value) {
        return forNumber(value);
      }

      public static EventsCase forNumber(int value) {
        switch (value) {
          case 3: return EVSIMPLEMESSAGE;
          case 4: return EVSIMPLENUMBER;
          case 0: return EVENTS_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public EventsCase
    getEventsCase() {
      return EventsCase.forNumber(
          eventsCase_);
    }

    public static final int SOURCE_FIELD_NUMBER = 1;
    private int source_;
    /**
     * <code>uint32 source = 1;</code>
     * @return The source.
     */
    @java.lang.Override
    public int getSource() {
      return source_;
    }

    public static final int DESTINATION_FIELD_NUMBER = 2;
    private int destination_;
    /**
     * <code>uint32 destination = 2;</code>
     * @return The destination.
     */
    @java.lang.Override
    public int getDestination() {
      return destination_;
    }

    public static final int EVSIMPLEMESSAGE_FIELD_NUMBER = 3;
    /**
     * <code>.events.EvSimpleMessage evSimpleMessage = 3;</code>
     * @return Whether the evSimpleMessage field is set.
     */
    @java.lang.Override
    public boolean hasEvSimpleMessage() {
      return eventsCase_ == 3;
    }
    /**
     * <code>.events.EvSimpleMessage evSimpleMessage = 3;</code>
     * @return The evSimpleMessage.
     */
    @java.lang.Override
    public com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage getEvSimpleMessage() {
      if (eventsCase_ == 3) {
         return (com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage) events_;
      }
      return com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage.getDefaultInstance();
    }
    /**
     * <code>.events.EvSimpleMessage evSimpleMessage = 3;</code>
     */
    @java.lang.Override
    public com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessageOrBuilder getEvSimpleMessageOrBuilder() {
      if (eventsCase_ == 3) {
         return (com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage) events_;
      }
      return com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage.getDefaultInstance();
    }

    public static final int EVSIMPLENUMBER_FIELD_NUMBER = 4;
    /**
     * <code>.events.EvSimpleNumber evSimpleNumber = 4;</code>
     * @return Whether the evSimpleNumber field is set.
     */
    @java.lang.Override
    public boolean hasEvSimpleNumber() {
      return eventsCase_ == 4;
    }
    /**
     * <code>.events.EvSimpleNumber evSimpleNumber = 4;</code>
     * @return The evSimpleNumber.
     */
    @java.lang.Override
    public com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber getEvSimpleNumber() {
      if (eventsCase_ == 4) {
         return (com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber) events_;
      }
      return com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber.getDefaultInstance();
    }
    /**
     * <code>.events.EvSimpleNumber evSimpleNumber = 4;</code>
     */
    @java.lang.Override
    public com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumberOrBuilder getEvSimpleNumberOrBuilder() {
      if (eventsCase_ == 4) {
         return (com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber) events_;
      }
      return com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (source_ != 0) {
        output.writeUInt32(1, source_);
      }
      if (destination_ != 0) {
        output.writeUInt32(2, destination_);
      }
      if (eventsCase_ == 3) {
        output.writeMessage(3, (com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage) events_);
      }
      if (eventsCase_ == 4) {
        output.writeMessage(4, (com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber) events_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (source_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, source_);
      }
      if (destination_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, destination_);
      }
      if (eventsCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage) events_);
      }
      if (eventsCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber) events_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.kylegagnon99.events.EvBaseOuterClass.EvBase)) {
        return super.equals(obj);
      }
      com.github.kylegagnon99.events.EvBaseOuterClass.EvBase other = (com.github.kylegagnon99.events.EvBaseOuterClass.EvBase) obj;

      if (getSource()
          != other.getSource()) return false;
      if (getDestination()
          != other.getDestination()) return false;
      if (!getEventsCase().equals(other.getEventsCase())) return false;
      switch (eventsCase_) {
        case 3:
          if (!getEvSimpleMessage()
              .equals(other.getEvSimpleMessage())) return false;
          break;
        case 4:
          if (!getEvSimpleNumber()
              .equals(other.getEvSimpleNumber())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource();
      hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
      hash = (53 * hash) + getDestination();
      switch (eventsCase_) {
        case 3:
          hash = (37 * hash) + EVSIMPLEMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getEvSimpleMessage().hashCode();
          break;
        case 4:
          hash = (37 * hash) + EVSIMPLENUMBER_FIELD_NUMBER;
          hash = (53 * hash) + getEvSimpleNumber().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.kylegagnon99.events.EvBaseOuterClass.EvBase parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.kylegagnon99.events.EvBaseOuterClass.EvBase parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.kylegagnon99.events.EvBaseOuterClass.EvBase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.kylegagnon99.events.EvBaseOuterClass.EvBase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.kylegagnon99.events.EvBaseOuterClass.EvBase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.kylegagnon99.events.EvBaseOuterClass.EvBase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.kylegagnon99.events.EvBaseOuterClass.EvBase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.kylegagnon99.events.EvBaseOuterClass.EvBase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.kylegagnon99.events.EvBaseOuterClass.EvBase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.kylegagnon99.events.EvBaseOuterClass.EvBase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.kylegagnon99.events.EvBaseOuterClass.EvBase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.kylegagnon99.events.EvBaseOuterClass.EvBase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.kylegagnon99.events.EvBaseOuterClass.EvBase prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code events.EvBase}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:events.EvBase)
        com.github.kylegagnon99.events.EvBaseOuterClass.EvBaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.kylegagnon99.events.EvBaseOuterClass.internal_static_events_EvBase_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.kylegagnon99.events.EvBaseOuterClass.internal_static_events_EvBase_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.kylegagnon99.events.EvBaseOuterClass.EvBase.class, com.github.kylegagnon99.events.EvBaseOuterClass.EvBase.Builder.class);
      }

      // Construct using com.github.kylegagnon99.events.EvBaseOuterClass.EvBase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        source_ = 0;

        destination_ = 0;

        eventsCase_ = 0;
        events_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.kylegagnon99.events.EvBaseOuterClass.internal_static_events_EvBase_descriptor;
      }

      @java.lang.Override
      public com.github.kylegagnon99.events.EvBaseOuterClass.EvBase getDefaultInstanceForType() {
        return com.github.kylegagnon99.events.EvBaseOuterClass.EvBase.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.kylegagnon99.events.EvBaseOuterClass.EvBase build() {
        com.github.kylegagnon99.events.EvBaseOuterClass.EvBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.kylegagnon99.events.EvBaseOuterClass.EvBase buildPartial() {
        com.github.kylegagnon99.events.EvBaseOuterClass.EvBase result = new com.github.kylegagnon99.events.EvBaseOuterClass.EvBase(this);
        result.source_ = source_;
        result.destination_ = destination_;
        if (eventsCase_ == 3) {
          if (evSimpleMessageBuilder_ == null) {
            result.events_ = events_;
          } else {
            result.events_ = evSimpleMessageBuilder_.build();
          }
        }
        if (eventsCase_ == 4) {
          if (evSimpleNumberBuilder_ == null) {
            result.events_ = events_;
          } else {
            result.events_ = evSimpleNumberBuilder_.build();
          }
        }
        result.eventsCase_ = eventsCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.kylegagnon99.events.EvBaseOuterClass.EvBase) {
          return mergeFrom((com.github.kylegagnon99.events.EvBaseOuterClass.EvBase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.kylegagnon99.events.EvBaseOuterClass.EvBase other) {
        if (other == com.github.kylegagnon99.events.EvBaseOuterClass.EvBase.getDefaultInstance()) return this;
        if (other.getSource() != 0) {
          setSource(other.getSource());
        }
        if (other.getDestination() != 0) {
          setDestination(other.getDestination());
        }
        switch (other.getEventsCase()) {
          case EVSIMPLEMESSAGE: {
            mergeEvSimpleMessage(other.getEvSimpleMessage());
            break;
          }
          case EVSIMPLENUMBER: {
            mergeEvSimpleNumber(other.getEvSimpleNumber());
            break;
          }
          case EVENTS_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.kylegagnon99.events.EvBaseOuterClass.EvBase parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.kylegagnon99.events.EvBaseOuterClass.EvBase) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int eventsCase_ = 0;
      private java.lang.Object events_;
      public EventsCase
          getEventsCase() {
        return EventsCase.forNumber(
            eventsCase_);
      }

      public Builder clearEvents() {
        eventsCase_ = 0;
        events_ = null;
        onChanged();
        return this;
      }


      private int source_ ;
      /**
       * <code>uint32 source = 1;</code>
       * @return The source.
       */
      @java.lang.Override
      public int getSource() {
        return source_;
      }
      /**
       * <code>uint32 source = 1;</code>
       * @param value The source to set.
       * @return This builder for chaining.
       */
      public Builder setSource(int value) {
        
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 source = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSource() {
        
        source_ = 0;
        onChanged();
        return this;
      }

      private int destination_ ;
      /**
       * <code>uint32 destination = 2;</code>
       * @return The destination.
       */
      @java.lang.Override
      public int getDestination() {
        return destination_;
      }
      /**
       * <code>uint32 destination = 2;</code>
       * @param value The destination to set.
       * @return This builder for chaining.
       */
      public Builder setDestination(int value) {
        
        destination_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 destination = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDestination() {
        
        destination_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage, com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage.Builder, com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessageOrBuilder> evSimpleMessageBuilder_;
      /**
       * <code>.events.EvSimpleMessage evSimpleMessage = 3;</code>
       * @return Whether the evSimpleMessage field is set.
       */
      @java.lang.Override
      public boolean hasEvSimpleMessage() {
        return eventsCase_ == 3;
      }
      /**
       * <code>.events.EvSimpleMessage evSimpleMessage = 3;</code>
       * @return The evSimpleMessage.
       */
      @java.lang.Override
      public com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage getEvSimpleMessage() {
        if (evSimpleMessageBuilder_ == null) {
          if (eventsCase_ == 3) {
            return (com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage) events_;
          }
          return com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage.getDefaultInstance();
        } else {
          if (eventsCase_ == 3) {
            return evSimpleMessageBuilder_.getMessage();
          }
          return com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.events.EvSimpleMessage evSimpleMessage = 3;</code>
       */
      public Builder setEvSimpleMessage(com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage value) {
        if (evSimpleMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          events_ = value;
          onChanged();
        } else {
          evSimpleMessageBuilder_.setMessage(value);
        }
        eventsCase_ = 3;
        return this;
      }
      /**
       * <code>.events.EvSimpleMessage evSimpleMessage = 3;</code>
       */
      public Builder setEvSimpleMessage(
          com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage.Builder builderForValue) {
        if (evSimpleMessageBuilder_ == null) {
          events_ = builderForValue.build();
          onChanged();
        } else {
          evSimpleMessageBuilder_.setMessage(builderForValue.build());
        }
        eventsCase_ = 3;
        return this;
      }
      /**
       * <code>.events.EvSimpleMessage evSimpleMessage = 3;</code>
       */
      public Builder mergeEvSimpleMessage(com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage value) {
        if (evSimpleMessageBuilder_ == null) {
          if (eventsCase_ == 3 &&
              events_ != com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage.getDefaultInstance()) {
            events_ = com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage.newBuilder((com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage) events_)
                .mergeFrom(value).buildPartial();
          } else {
            events_ = value;
          }
          onChanged();
        } else {
          if (eventsCase_ == 3) {
            evSimpleMessageBuilder_.mergeFrom(value);
          }
          evSimpleMessageBuilder_.setMessage(value);
        }
        eventsCase_ = 3;
        return this;
      }
      /**
       * <code>.events.EvSimpleMessage evSimpleMessage = 3;</code>
       */
      public Builder clearEvSimpleMessage() {
        if (evSimpleMessageBuilder_ == null) {
          if (eventsCase_ == 3) {
            eventsCase_ = 0;
            events_ = null;
            onChanged();
          }
        } else {
          if (eventsCase_ == 3) {
            eventsCase_ = 0;
            events_ = null;
          }
          evSimpleMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.events.EvSimpleMessage evSimpleMessage = 3;</code>
       */
      public com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage.Builder getEvSimpleMessageBuilder() {
        return getEvSimpleMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.events.EvSimpleMessage evSimpleMessage = 3;</code>
       */
      @java.lang.Override
      public com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessageOrBuilder getEvSimpleMessageOrBuilder() {
        if ((eventsCase_ == 3) && (evSimpleMessageBuilder_ != null)) {
          return evSimpleMessageBuilder_.getMessageOrBuilder();
        } else {
          if (eventsCase_ == 3) {
            return (com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage) events_;
          }
          return com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.events.EvSimpleMessage evSimpleMessage = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage, com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage.Builder, com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessageOrBuilder> 
          getEvSimpleMessageFieldBuilder() {
        if (evSimpleMessageBuilder_ == null) {
          if (!(eventsCase_ == 3)) {
            events_ = com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage.getDefaultInstance();
          }
          evSimpleMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage, com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage.Builder, com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessageOrBuilder>(
                  (com.github.kylegagnon99.events.EvSimpleMessageOuterClass.EvSimpleMessage) events_,
                  getParentForChildren(),
                  isClean());
          events_ = null;
        }
        eventsCase_ = 3;
        onChanged();;
        return evSimpleMessageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber, com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber.Builder, com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumberOrBuilder> evSimpleNumberBuilder_;
      /**
       * <code>.events.EvSimpleNumber evSimpleNumber = 4;</code>
       * @return Whether the evSimpleNumber field is set.
       */
      @java.lang.Override
      public boolean hasEvSimpleNumber() {
        return eventsCase_ == 4;
      }
      /**
       * <code>.events.EvSimpleNumber evSimpleNumber = 4;</code>
       * @return The evSimpleNumber.
       */
      @java.lang.Override
      public com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber getEvSimpleNumber() {
        if (evSimpleNumberBuilder_ == null) {
          if (eventsCase_ == 4) {
            return (com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber) events_;
          }
          return com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber.getDefaultInstance();
        } else {
          if (eventsCase_ == 4) {
            return evSimpleNumberBuilder_.getMessage();
          }
          return com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber.getDefaultInstance();
        }
      }
      /**
       * <code>.events.EvSimpleNumber evSimpleNumber = 4;</code>
       */
      public Builder setEvSimpleNumber(com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber value) {
        if (evSimpleNumberBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          events_ = value;
          onChanged();
        } else {
          evSimpleNumberBuilder_.setMessage(value);
        }
        eventsCase_ = 4;
        return this;
      }
      /**
       * <code>.events.EvSimpleNumber evSimpleNumber = 4;</code>
       */
      public Builder setEvSimpleNumber(
          com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber.Builder builderForValue) {
        if (evSimpleNumberBuilder_ == null) {
          events_ = builderForValue.build();
          onChanged();
        } else {
          evSimpleNumberBuilder_.setMessage(builderForValue.build());
        }
        eventsCase_ = 4;
        return this;
      }
      /**
       * <code>.events.EvSimpleNumber evSimpleNumber = 4;</code>
       */
      public Builder mergeEvSimpleNumber(com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber value) {
        if (evSimpleNumberBuilder_ == null) {
          if (eventsCase_ == 4 &&
              events_ != com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber.getDefaultInstance()) {
            events_ = com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber.newBuilder((com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber) events_)
                .mergeFrom(value).buildPartial();
          } else {
            events_ = value;
          }
          onChanged();
        } else {
          if (eventsCase_ == 4) {
            evSimpleNumberBuilder_.mergeFrom(value);
          }
          evSimpleNumberBuilder_.setMessage(value);
        }
        eventsCase_ = 4;
        return this;
      }
      /**
       * <code>.events.EvSimpleNumber evSimpleNumber = 4;</code>
       */
      public Builder clearEvSimpleNumber() {
        if (evSimpleNumberBuilder_ == null) {
          if (eventsCase_ == 4) {
            eventsCase_ = 0;
            events_ = null;
            onChanged();
          }
        } else {
          if (eventsCase_ == 4) {
            eventsCase_ = 0;
            events_ = null;
          }
          evSimpleNumberBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.events.EvSimpleNumber evSimpleNumber = 4;</code>
       */
      public com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber.Builder getEvSimpleNumberBuilder() {
        return getEvSimpleNumberFieldBuilder().getBuilder();
      }
      /**
       * <code>.events.EvSimpleNumber evSimpleNumber = 4;</code>
       */
      @java.lang.Override
      public com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumberOrBuilder getEvSimpleNumberOrBuilder() {
        if ((eventsCase_ == 4) && (evSimpleNumberBuilder_ != null)) {
          return evSimpleNumberBuilder_.getMessageOrBuilder();
        } else {
          if (eventsCase_ == 4) {
            return (com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber) events_;
          }
          return com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber.getDefaultInstance();
        }
      }
      /**
       * <code>.events.EvSimpleNumber evSimpleNumber = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber, com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber.Builder, com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumberOrBuilder> 
          getEvSimpleNumberFieldBuilder() {
        if (evSimpleNumberBuilder_ == null) {
          if (!(eventsCase_ == 4)) {
            events_ = com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber.getDefaultInstance();
          }
          evSimpleNumberBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber, com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber.Builder, com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumberOrBuilder>(
                  (com.github.kylegagnon99.events.EvSimpleNumberOuterClass.EvSimpleNumber) events_,
                  getParentForChildren(),
                  isClean());
          events_ = null;
        }
        eventsCase_ = 4;
        onChanged();;
        return evSimpleNumberBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:events.EvBase)
    }

    // @@protoc_insertion_point(class_scope:events.EvBase)
    private static final com.github.kylegagnon99.events.EvBaseOuterClass.EvBase DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.kylegagnon99.events.EvBaseOuterClass.EvBase();
    }

    public static com.github.kylegagnon99.events.EvBaseOuterClass.EvBase getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EvBase>
        PARSER = new com.google.protobuf.AbstractParser<EvBase>() {
      @java.lang.Override
      public EvBase parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EvBase(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EvBase> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EvBase> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.kylegagnon99.events.EvBaseOuterClass.EvBase getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_EvBase_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_events_EvBase_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014EvBase.proto\022\006events\032\025EvSimpleMessage." +
      "proto\032\024EvSimpleNumber.proto\"\235\001\n\006EvBase\022\016" +
      "\n\006source\030\001 \001(\r\022\023\n\013destination\030\002 \001(\r\0222\n\017e" +
      "vSimpleMessage\030\003 \001(\0132\027.events.EvSimpleMe" +
      "ssageH\000\0220\n\016evSimpleNumber\030\004 \001(\0132\026.events" +
      ".EvSimpleNumberH\000B\010\n\006eventsB \n\036com.githu" +
      "b.kylegagnon99.eventsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.kylegagnon99.events.EvSimpleMessageOuterClass.getDescriptor(),
          com.github.kylegagnon99.events.EvSimpleNumberOuterClass.getDescriptor(),
        });
    internal_static_events_EvBase_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_events_EvBase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_events_EvBase_descriptor,
        new java.lang.String[] { "Source", "Destination", "EvSimpleMessage", "EvSimpleNumber", "Events", });
    com.github.kylegagnon99.events.EvSimpleMessageOuterClass.getDescriptor();
    com.github.kylegagnon99.events.EvSimpleNumberOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
