# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EvBase.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import EvSimpleMessage_pb2 as EvSimpleMessage__pb2
import EvSimpleNumber_pb2 as EvSimpleNumber__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x45vBase.proto\x12\x06\x65vents\x1a\x15\x45vSimpleMessage.proto\x1a\x14\x45vSimpleNumber.proto\"\x9d\x01\n\x06\x45vBase\x12\x0e\n\x06source\x18\x01 \x01(\r\x12\x13\n\x0b\x64\x65stination\x18\x02 \x01(\r\x12\x32\n\x0f\x65vSimpleMessage\x18\x03 \x01(\x0b\x32\x17.events.EvSimpleMessageH\x00\x12\x30\n\x0e\x65vSimpleNumber\x18\x04 \x01(\x0b\x32\x16.events.EvSimpleNumberH\x00\x42\x08\n\x06\x65ventsB \n\x1e\x63om.github.kylegagnon99.eventsb\x06proto3')



_EVBASE = DESCRIPTOR.message_types_by_name['EvBase']
EvBase = _reflection.GeneratedProtocolMessageType('EvBase', (_message.Message,), {
  'DESCRIPTOR' : _EVBASE,
  '__module__' : 'EvBase_pb2'
  # @@protoc_insertion_point(class_scope:events.EvBase)
  })
_sym_db.RegisterMessage(EvBase)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.github.kylegagnon99.events'
  _EVBASE._serialized_start=70
  _EVBASE._serialized_end=227
# @@protoc_insertion_point(module_scope)
