# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EvSimpleMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x45vSimpleMessage.proto\x12\x06\x65vents\"\"\n\x0f\x45vSimpleMessage\x12\x0f\n\x07message\x18\x01 \x01(\tB \n\x1e\x63om.github.kylegagnon99.eventsb\x06proto3')



_EVSIMPLEMESSAGE = DESCRIPTOR.message_types_by_name['EvSimpleMessage']
EvSimpleMessage = _reflection.GeneratedProtocolMessageType('EvSimpleMessage', (_message.Message,), {
  'DESCRIPTOR' : _EVSIMPLEMESSAGE,
  '__module__' : 'EvSimpleMessage_pb2'
  # @@protoc_insertion_point(class_scope:events.EvSimpleMessage)
  })
_sym_db.RegisterMessage(EvSimpleMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.github.kylegagnon99.events'
  _EVSIMPLEMESSAGE._serialized_start=33
  _EVSIMPLEMESSAGE._serialized_end=67
# @@protoc_insertion_point(module_scope)
