# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EvSimpleNumber.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x45vSimpleNumber.proto\x12\x06\x65vents\" \n\x0e\x45vSimpleNumber\x12\x0e\n\x06number\x18\x01 \x01(\x05\x42 \n\x1e\x63om.github.kylegagnon99.eventsb\x06proto3')



_EVSIMPLENUMBER = DESCRIPTOR.message_types_by_name['EvSimpleNumber']
EvSimpleNumber = _reflection.GeneratedProtocolMessageType('EvSimpleNumber', (_message.Message,), {
  'DESCRIPTOR' : _EVSIMPLENUMBER,
  '__module__' : 'EvSimpleNumber_pb2'
  # @@protoc_insertion_point(class_scope:events.EvSimpleNumber)
  })
_sym_db.RegisterMessage(EvSimpleNumber)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.github.kylegagnon99.events'
  _EVSIMPLENUMBER._serialized_start=32
  _EVSIMPLENUMBER._serialized_end=64
# @@protoc_insertion_point(module_scope)
