// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EvSimpleNumber.proto

#include "EvSimpleNumber.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace events {
constexpr EvSimpleNumber::EvSimpleNumber(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : number_(0){}
struct EvSimpleNumberDefaultTypeInternal {
  constexpr EvSimpleNumberDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~EvSimpleNumberDefaultTypeInternal() {}
  union {
    EvSimpleNumber _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT EvSimpleNumberDefaultTypeInternal _EvSimpleNumber_default_instance_;
}  // namespace events
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_EvSimpleNumber_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_EvSimpleNumber_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_EvSimpleNumber_2eproto = nullptr;

const uint32_t TableStruct_EvSimpleNumber_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::events::EvSimpleNumber, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::events::EvSimpleNumber, number_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::events::EvSimpleNumber)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::events::_EvSimpleNumber_default_instance_),
};

const char descriptor_table_protodef_EvSimpleNumber_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024EvSimpleNumber.proto\022\006events\" \n\016EvSimp"
  "leNumber\022\016\n\006number\030\001 \001(\005B \n\036com.github.k"
  "ylegagnon99.eventsb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_EvSimpleNumber_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_EvSimpleNumber_2eproto = {
  false, false, 106, descriptor_table_protodef_EvSimpleNumber_2eproto, "EvSimpleNumber.proto", 
  &descriptor_table_EvSimpleNumber_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_EvSimpleNumber_2eproto::offsets,
  file_level_metadata_EvSimpleNumber_2eproto, file_level_enum_descriptors_EvSimpleNumber_2eproto, file_level_service_descriptors_EvSimpleNumber_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_EvSimpleNumber_2eproto_getter() {
  return &descriptor_table_EvSimpleNumber_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_EvSimpleNumber_2eproto(&descriptor_table_EvSimpleNumber_2eproto);
namespace events {

// ===================================================================

class EvSimpleNumber::_Internal {
 public:
};

EvSimpleNumber::EvSimpleNumber(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:events.EvSimpleNumber)
}
EvSimpleNumber::EvSimpleNumber(const EvSimpleNumber& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  number_ = from.number_;
  // @@protoc_insertion_point(copy_constructor:events.EvSimpleNumber)
}

inline void EvSimpleNumber::SharedCtor() {
number_ = 0;
}

EvSimpleNumber::~EvSimpleNumber() {
  // @@protoc_insertion_point(destructor:events.EvSimpleNumber)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void EvSimpleNumber::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void EvSimpleNumber::ArenaDtor(void* object) {
  EvSimpleNumber* _this = reinterpret_cast< EvSimpleNumber* >(object);
  (void)_this;
}
void EvSimpleNumber::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void EvSimpleNumber::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void EvSimpleNumber::Clear() {
// @@protoc_insertion_point(message_clear_start:events.EvSimpleNumber)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  number_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EvSimpleNumber::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 number = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          number_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EvSimpleNumber::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:events.EvSimpleNumber)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 number = 1;
  if (this->_internal_number() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_number(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:events.EvSimpleNumber)
  return target;
}

size_t EvSimpleNumber::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:events.EvSimpleNumber)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 number = 1;
  if (this->_internal_number() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_number());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EvSimpleNumber::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    EvSimpleNumber::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EvSimpleNumber::GetClassData() const { return &_class_data_; }

void EvSimpleNumber::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<EvSimpleNumber *>(to)->MergeFrom(
      static_cast<const EvSimpleNumber &>(from));
}


void EvSimpleNumber::MergeFrom(const EvSimpleNumber& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:events.EvSimpleNumber)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_number() != 0) {
    _internal_set_number(from._internal_number());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EvSimpleNumber::CopyFrom(const EvSimpleNumber& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:events.EvSimpleNumber)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EvSimpleNumber::IsInitialized() const {
  return true;
}

void EvSimpleNumber::InternalSwap(EvSimpleNumber* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(number_, other->number_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EvSimpleNumber::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_EvSimpleNumber_2eproto_getter, &descriptor_table_EvSimpleNumber_2eproto_once,
      file_level_metadata_EvSimpleNumber_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace events
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::events::EvSimpleNumber* Arena::CreateMaybeMessage< ::events::EvSimpleNumber >(Arena* arena) {
  return Arena::CreateMessageInternal< ::events::EvSimpleNumber >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
